services:
  postgres:
    image: postgres:15
    container_name: autoestudo-postgres
    environment:
      POSTGRES_USER: autoestudo_user
      POSTGRES_PASSWORD: autoestudo_pass
      POSTGRES_DB: autoestudo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge
